export const COUCHBASE_OPTIONS = "COUCHBASE_OPTIONS"
export const COUCHBASE_CLUSTER = "COUCHBASE_CLUSTER"
export const COUCHBASE_BUCKET = "COUCHBASE_BUCKET"
export const SCHEMA_KEY = "couchbase:schema"
export const PROP_METADATA_KEY = "couchbase:props"
export const PROP_UNIQUE_INDEXES_KEY = "couchbase:unique_indexes"
export const RELATIONS_KEY = "couchbase:relations"
